export default {
  dokument: {
    hlavicka: {
      typDP: {
        rdp: "1",
        odp: "0",
        ddp: "0",
      },
      zdanovacieObdobie: {
        rok: "2019",
      },
      skNace: {},
      adresaTrvPobytu: {},
      nerezident: "0",
      prepojeniePar2: "0",
      adresaObvPobytu: {},
      zastupca: {},
    },
    telo: {
      r29: "0",
      r31: {},
      r32: {
        uplatnujemNCZDNaManzela: "0",
      },
      r33: {
        uplatNCZDNaKupelStarostlivost: "0",
      },
      r34: {
        dieta: [
          {
            kupelnaStarostlivost: "0",
            m00: "0",
            m01: "0",
            m02: "0",
            m03: "0",
            m04: "0",
            m05: "0",
            m06: "0",
            m07: "0",
            m08: "0",
            m09: "0",
            m10: "0",
            m11: "0",
            m12: "0",
          },
          {
            kupelnaStarostlivost: "0",
            m00: "0",
            m01: "0",
            m02: "0",
            m03: "0",
            m04: "0",
            m05: "0",
            m06: "0",
            m07: "0",
            m08: "0",
            m09: "0",
            m10: "0",
            m11: "0",
            m12: "0",
          },
          {
            kupelnaStarostlivost: "0",
            m00: "0",
            m01: "0",
            m02: "0",
            m03: "0",
            m04: "0",
            m05: "0",
            m06: "0",
            m07: "0",
            m08: "0",
            m09: "0",
            m10: "0",
            m11: "0",
            m12: "0",
          },
          {
            kupelnaStarostlivost: "0",
            m00: "0",
            m01: "0",
            m02: "0",
            m03: "0",
            m04: "0",
            m05: "0",
            m06: "0",
            m07: "0",
            m08: "0",
            m09: "0",
            m10: "0",
            m11: "0",
            m12: "0",
          },
        ],
      },
      r35udajeDalsieDeti: "0",
      r37: {
        uplatDanBonusZaplatUroky: "0",
      },
      tabulka1: {
        t1r1: {},
        t1r2: {},
        t1r3: {},
        t1r4: {},
        t1r5: {},
        t1r6: {},
        t1r7: {},
        t1r8: {},
        t1r9: {},
        t1r10: {},
        t1r11: {},
        t1r12: {},
        t1r13: {},
      },
      vydavkyPar6ods11_ods1a2: "0",
      vydavkyPar6ods11_ods3: "0",
      vydavkyPar6ods11_ods4: "0",
      vydavkyPar6ods10_ods1a2: "0",
      vydavkyPar6ods10_ods4: "0",
      uplatnujemPar17ods17_ods1a2: "0",
      uplatnujemPar17ods17_ods3a4: "0",
      ukoncujemUplatnovaniePar17ods17_ods1a2: "0",
      ukoncujemUplatnovaniePar17ods17_ods3a4: "0",
      tabulka1a: {
        t1r1: {},
        t1r2: {},
        t1r3: {},
        t1r4: {},
        t1r5: {},
      },
      tabulka1b: {
        t1r1: {},
        t1r2: {},
      },
      r49: {
        predchObdobie: {},
      },
      r50: {
        predchObdobie: {},
      },
      r51: {
        predchObdobie: {},
      },
      r52: {
        predchObdobie: {},
      },
      tabulka2: {
        t2r1: {},
        t2r2: {},
        t2r3: {},
        t2r4: {},
        t2r5: {},
        t2r6: {},
        t2r7: {},
        t2r8: {},
        t2r9: {},
        t2r10: {},
        t2r11: {},
        t2r12: {},
      },
      tabulka3: {
        t3r1: {},
        t3r2: {},
        t3r3: {},
        t3r4: {},
        t3r5: {},
        t3r6: {},
        t3r7: {},
        t3r8: {},
        t3r9: {},
        t3r10: {},
        t3r11: {},
        t3r12: {},
        t3r13: {},
        t3r14: {},
        t3r15: {},
        t3r16: {},
        t3r17: {},
        t3r18: {},
        t3r19: {},
      },
      r139: "0",
      neuplatnujem: "0",
      splnam3per: "0",
      r142: {
        obchMeno: {},
        suhlasZaslUdaje: "0",
      },
      osobitneZaznamy: {
        uvadza: "0",
        udajeOprijmoch: [{}, {}, {}, {}, {}, {}],
        rekreaciaPar19ods2: "0",
      },
      r143: "3",
      datumVyhlasenia: "20.02.2020",
      danovyPreplatokBonus: {
        vyplatitDanovyBonus: "0",
        vyplatitDanovyBonusUroky: "0",
        vratitDanPreplatok: "0",
        sposobPlatby: {
          poukazka: "0",
          ucet: "0",
          ucetZahranicie: "0",
        },
        bankovyUcet: {},
      },
      prilPodielyNaZisku: {
        pr4: {},
        pr5: {},
        pr6: {},
        pr8: "7",
        pr22: {},
        pr23: {},
        pr24: {},
        pr26: "35",
      },
      socZdravPoistenie: {
        pr1: {},
        priPrimoch6ods1a2VediemPU: "0",
      },
    },
  },
};
