// Generated by the amazing http://json2ts.com/

export interface TypDP {
  rdp: string
  odp: string
  ddp: string
}

export interface ZdanovacieObdobie {
  rok: string
  datumDDP: string
}

export interface SkNace {
  k1: string
  k2: string
  k3: string
  cinnost: string
}

export interface AdresaTrvPobytu {
  ulica: string
  cislo: string
  psc: string
  obec: string
  stat: string
}

export interface AdresaObvPobytu {
  ulica: string
  cislo: string
  psc: string
  obec: string
}

export interface Zastupca {
  priezvisko: string
  meno: string
  titul: string
  titulZa: string
  rodneCislo: string
  ulica: string
  cislo: string
  psc: string
  obec: string
  stat: string
  tel: string
  email: string
}

export interface Hlavicka {
  dic: string
  datumNarodenia: string
  typDP: TypDP
  zdanovacieObdobie: ZdanovacieObdobie
  skNace: SkNace
  priezvisko: string
  meno: string
  titul: string
  titulZa: string
  adresaTrvPobytu: AdresaTrvPobytu
  nerezident: string
  prepojeniePar2: string
  adresaObvPobytu: AdresaObvPobytu
  zastupca: Zastupca
}

export interface R31 {
  priezviskoMeno: string
  rodneCislo: string
}

export interface R32 {
  uplatnujemNCZDNaManzela: string
  vlastnePrijmy: string
  pocetMesiacov: string
}

export interface Dieta {
  priezviskoMeno: string
  rodneCislo: string
  m00: string
  m01: string
  m02: string
  m03: string
  m04: string
  m05: string
  m06: string
  m07: string
  m08: string
  m09: string
  m10: string
  m11: string
  m12: string
}

export interface R35 {
  uplatDanBonusZaplatUroky: string
  zaplateneUroky: string
  pocetMesiacov: string
  datumZacatiaUroceniaUveru: string
}

export interface T1r1 {
  s1: string
  s2: string
}

export interface T1r2 {
  s1: string
  s2: string
}

export interface T1r3 {
  s1: string
  s2: string
}

export interface T1r4 {
  s1: string
  s2: string
}

export interface T1r5 {
  s1: string
  s2: string
}

export interface T1r6 {
  s1: string
  s2: string
}

export interface T1r7 {
  s1: string
  s2: string
}

export interface T1r8 {
  s1: string
  s2: string
}

export interface T1r9 {
  s1: string
  s2: string
}

export interface T1r10 {
  s1: string
  s2: string
}

export interface T1r11 {
  s1: string
  s2: string
}

export interface T1r12 {
  s1: string
  s2: string
}

export interface T1r13 {
  s1: string
  s2: string
}

export interface Tabulka1 {
  t1r1: T1r1
  t1r2: T1r2
  t1r3: T1r3
  t1r4: T1r4
  t1r5: T1r5
  t1r6: T1r6
  t1r7: T1r7
  t1r8: T1r8
  t1r9: T1r9
  t1r10: T1r10
  t1r11: T1r11
  t1r12: T1r12
  t1r13: T1r13
}

export interface T1r14 {
  s1: string
  s2: string
}

export interface T1r22 {
  s1: string
  s2: string
}

export interface T1r32 {
  s1: string
  s2: string
}

export interface T1r42 {
  s1: string
  s2: string
}

export interface T1r52 {
  s1: string
  s2: string
}

export interface Tabulka1a {
  t1r1: T1r14
  t1r2: T1r22
  t1r3: T1r32
  t1r4: T1r42
  t1r5: T1r52
}

export interface T1r15 {
  s1: string
  s2: string
}

export interface T1r23 {
  s1: string
  s2: string
}

export interface Tabulka1b {
  t1r1: T1r15
  t1r2: T1r23
}

export interface Udaje {
  r02: string
  r03: string
  r04: string
}

export interface R4 {
  rok: string
  udaje: Udaje
}

export interface Udaje2 {
  r02: string
  r03: string
}

interface R49 {
  rok: string
  udaje: Udaje
}

export interface R50 {
  rok: string
  udaje: Udaje
}
export interface R51 {
  rok: string
  udaje: Udaje2
}

export interface T2r1 {
  s1: string
  s2: string
}

export interface T2r2 {
  s1: string
  s2: string
}

export interface T2r3 {
  s1: string
  s2: string
}

export interface T2r4 {
  s1: string
  s2: string
}

export interface T2r5 {
  s1: string
  s2: string
}

export interface T2r6 {
  s1: string
  s2: string
}

export interface T2r7 {
  s1: string
  s2: string
}

export interface T2r8 {
  s1: string
  s2: string
}

export interface T2r9 {
  s1: string
  s2: string
}

export interface T2r10 {
  s1: string
  s2: string
}

export interface T2r11 {
  s1: string
  s2: string
}

export interface T2r12 {
  s1: string
}

export interface Tabulka2 {
  t2r1: T2r1
  t2r2: T2r2
  t2r3: T2r3
  t2r4: T2r4
  t2r5: T2r5
  t2r6: T2r6
  t2r7: T2r7
  t2r8: T2r8
  t2r9: T2r9
  t2r10: T2r10
  t2r11: T2r11
  t2r12: T2r12
}

export interface T3r1 {
  s1: string
  s2: string
}

export interface T3r2 {
  s1: string
  s2: string
}

export interface T3r3 {
  s1: string
  s2: string
}

export interface T3r4 {
  s1: string
  s2: string
}

export interface T3r5 {
  s1: string
  s2: string
}

export interface T3r6 {
  s1: string
  s2: string
}

export interface T3r7 {
  s1: string
  s2: string
}

export interface T3r8 {
  s1: string
  s2: string
}

export interface T3r9 {
  s1: string
  s2: string
}

export interface T3r10 {
  s1: string
  s2: string
}

export interface T3r11 {
  s1: string
  s2: string
}

export interface T3r12 {
  s1: string
  s2: string
}

export interface T3r13 {
  s1: string
  s2: string
}

export interface T3r14 {
  s1: string
  s2: string
}

export interface T3r15 {
  s1: string
  s2: string
}

export interface T3r16 {
  s1: string
  s2: string
}

export interface T3r17 {
  s1: string
  s2: string
}

export interface T3r18 {
  s1: string
}

export interface T3r19 {
  s1: string
  s2: string
}

export interface Tabulka3 {
  t3r1: T3r1
  t3r2: T3r2
  t3r3: T3r3
  t3r4: T3r4
  t3r5: T3r5
  t3r6: T3r6
  t3r7: T3r7
  t3r8: T3r8
  t3r9: T3r9
  t3r10: T3r10
  t3r11: T3r11
  t3r12: T3r12
  t3r13: T3r13
  t3r14: T3r14
  t3r15: T3r15
  t3r16: T3r16
  t3r17: T3r17
  t3r18: T3r18
  t3r19: T3r19
}

export interface R152 {
  ico: string
  obchMeno: {
    riadok: string[]
  }
  suhlasZaslUdaje: string
}

export interface UdajeOprijmoch {
  kodStatu: string
  druhPrimuPar: string
  druhPrimuOds: string
  druhPrimuPis: string
  prijmy: string
  vydavky: string
  zTohoVydavky: string
}

export interface OsobitneZaznamy {
  uvadza: string
  udajeOprijmoch: UdajeOprijmoch[]
  rekreaciaPar19ods2: string
  rekreaciaSuma: string
  zaznamy: string
}

export interface SposobPlatby {
  poukazka: string
  ucet: string
  ucetZahranicie: string
}

export interface BankovyUcet {
  IBAN: string
}

export interface DanovyPreplatokBonus {
  vyplatitDanovyBonus: string
  vyplatitDanovyBonusUroky: string
  vratitDanPreplatok: string
  sposobPlatby: SposobPlatby
  bankovyUcet: BankovyUcet
  datum: string
}

interface PrilPar30cOdpocetVydavkovRiadok {
  zdanObdobieOd: string
  zdanObdobieDo: string
  narok: string
  odpocitanaCast: string
}

interface PrilPar30cOdpocetVydavkov {
  projektCislo: string
  pocetProjektov: string
  datumRealizacie: string
  r01: PrilPar30cOdpocetVydavkovRiadok
  r02: PrilPar30cOdpocetVydavkovRiadok
  r03: PrilPar30cOdpocetVydavkovRiadok
  r04: PrilPar30cOdpocetVydavkovRiadok
  r05: PrilPar30cOdpocetVydavkovRiadok
  r06: string
  ciele: string
  r07: string
  r08: string
  r09: string
}

interface Pril1bPar30eVydavkyInvesticieRiadok {
  s01Od: string
  s01Do: string
  s02: string
  s03: string
  s04: string
}

interface Pril1bPar30eVydavkyInvesticie {
  r01: Pril1bPar30eVydavkyInvesticieRiadok
  r02: Pril1bPar30eVydavkyInvesticieRiadok
  r03: Pril1bPar30eVydavkyInvesticieRiadok
  r04: Pril1bPar30eVydavkyInvesticieRiadok
  r05: Pril1bPar30eVydavkyInvesticieRiadok
  r06: Pril1bPar30eVydavkyInvesticieRiadok
  r07: Pril1bPar30eVydavkyInvesticieRiadok
  r08: Pril1bPar30eVydavkyInvesticieRiadok
  r09: Pril1bPar30eVydavkyInvesticieRiadok
  r10: Pril1bPar30eVydavkyInvesticieRiadok
  r11: string
  r12: string
}

export interface Pr4 {
  s1: string
  s2: string
}

export interface Pr5 {
  s1: string
  s2: string
}

export interface Pr6 {
  s1: string
  s2: string
}

export interface Pr22 {
  s1: string
  s2: string
}

export interface Pr23 {
  s1: string
  s2: string
}

export interface Pr24 {
  s1: string
  s2: string
}

export interface PrilPodielyNaZisku {
  pr1: string
  pr2: string
  pr3: string
  pr4: Pr4
  pr5: Pr5
  pr6: Pr6
  pr7: string
  pr8: string
  pr9: string
  pr10: string
  pr11: string
  pr12: string
  pr13: string
  pr14: string
  pr15: string
  pr16: string
  pr17: string
  pr18: string
  pr19: string
  pr20: string
  pr21: string
  pr22: Pr22
  pr23: Pr23
  pr24: Pr24
  pr25: string
  pr26: string
  pr27: string
  pr28: string
}

export interface Pr1 {
  s1: string
  s2: string
}

export interface SocZdravPoistenie {
  pr1: Pr1
  pr2: string
  pr3: string
  pr4: string
  pr5: string
  pr6: string
  pr7: string
  pr8: string
  pr9: string
  pr10: string
  pr11: string
  pr12: string
  pr13: string
  pr14: string
  pr15: string
  priPrimoch6ods1a2VediemPU: string
  datum: string
}

interface R34 {
  priezviskoMeno: string
  rodneCislo: string
  m00: string
  m01: string
  m02: string
  m03: string
  m04: string
  m05: string
  m06: string
  m07: string
  m08: string
  m09: string
  m10: string
  m11: string
  m12: string
  druhaOsobaPodalaDPvSR: string
  dokladRocZuct: string
  dokladVyskaDane: string
}

export interface Telo {
  r29: string
  r30: string
  r31: R31
  r32: R32
  r33: { dieta: Dieta[] }
  r33a: string
  uplatnujemPar33Ods8: string
  r34: R34
  r34a: string
  r35: R35
  r36: string
  r36a: string
  r37: string
  r38: string
  tabulka1: Tabulka1
  mikrodanovnikPar2w: string
  vydavkyPar6ods11_ods1a2: string
  vydavkyPar6ods11_ods3: string
  vydavkyPar6ods11_ods4: string
  vydavkyPar6ods10_ods1a2: string
  vydavkyPar6ods10_ods4: string
  vydavkyPoistPar6ods11_ods1a2: string
  uplatnujemPar17ods17_ods1a2: string
  uplatnujemPar17ods17_ods3a4: string
  ukoncujemUplatnovaniePar17ods17_ods1a2: string
  ukoncujemUplatnovaniePar17ods17_ods3a4: string
  tabulka1a: Tabulka1a
  tabulka1b: Tabulka1b
  r39: string
  r40: string
  r41: string
  r42: string
  r43: string
  r44: string
  r45: string
  r46: string
  r47: string
  r48: string
  r49: R49
  r50: R50
  r51: R51
  r52: string
  r52a: string
  r53: string
  r54: string
  r55: string
  r56: string
  r57: string
  r58: string
  r59: string
  r60: string
  r61: string
  r62: string
  r63: string
  r64: string
  r65: string
  tabulka2: Tabulka2
  r66: string
  r67: string
  r68: string
  tabulka3: Tabulka3
  r69: string
  r70: string
  r71: string
  r72: string
  r73: string
  r74: string
  r75: string
  r77: string
  r78: string
  r79: string
  r80: string
  r81: string
  r82: string
  r83: string
  r84: string
  r85: string
  r86: string
  r87: string
  r88: string
  r89: string
  r90: string
  r91: string
  r92: string
  r93: string
  r94: string
  r95: string
  r96: string
  r97: string
  r98: string
  r99: string
  r100: string
  r101: string
  r102: string
  r103: string
  r104: string
  r105: string
  r106: string
  r107: string
  r108: string
  r109: string
  r110: string
  r111: string
  r112: string
  r113: string
  r114: string
  r115: string
  r116: string
  r116a: string
  r117: string
  r118: string
  r119: string
  r120: string
  r121: string
  r122: string
  r123: string
  r124: string
  r125: string
  r126: string
  r127: string
  r128: string
  r129: string
  r130: string
  r131: string
  r132: string
  r133: string
  r134: string
  r135: string
  r136: string
  r137: string
  r138: string
  r139: string
  r140: string
  r141: string
  r142: string
  r143: string
  r144: string
  r145: string
  r146: string
  r147: string
  r148: string
  r149: string
  r150: string
  neuplatnujem: string
  splnam3per: string
  r151: string
  r152: R152
  cbPriPrijmoch11Ods6Zak1a2: string
  cbPriPrijmoch11Ods6Zak4: string
  cbPriPrijmoch11Ods6Zak3: string
  osobitneZaznamy: OsobitneZaznamy
  r153: string
  datumVyhlasenia: string
  danovyPreplatokBonus: DanovyPreplatokBonus
  prilPar30cOdpocetVydavkov: PrilPar30cOdpocetVydavkov
  pril1bPar30eVydavkyInvesticie: Pril1bPar30eVydavkyInvesticie
  prilPodielyNaZisku: PrilPodielyNaZisku
  socZdravPoistenie: SocZdravPoistenie
}

export interface Dokument {
  hlavicka: Hlavicka
  telo: Telo
}

export interface OutputJson {
  dokument: Dokument
}
