/*
  all posible values from postpone from state select
  [...document.getElementsByName("tbTPStat")[0].getElementsByTagName("option")].map((o) => o.value)
*/
export const countries: string[] = [
  '',
  'Slovensko',
  'Andorra',
  'Spojené arabské emiráty',
  'Afganistan',
  'Antigua a Barbuda',
  'Anguilla',
  'Albánsko',
  'Arménsko',
  'Angola',
  'Antarktída',
  'Argentína',
  'Americká Samoa',
  'Rakúsko',
  'Austrália',
  'Aruba',
  'Alandy',
  'Azerbajdžan',
  'Bosna a Hercegovina',
  'Barbados',
  'Bangladéš',
  'Belgicko',
  'Burkina',
  'Bulharsko',
  'Bahrajn',
  'Burundi',
  'Benin',
  'Svätý Bartolomej',
  'Bermudy',
  'Brunej',
  'Bolívia',
  'Bonaire, Svätý Eustach a Saba',
  'Brazília',
  'Bahamy',
  'Bhután',
  'Bouvetov ostrov',
  'Botswana',
  'Bielorusko',
  'Belize',
  'Kanada',
  'Kokosové ostrovy',
  'Kongo (býv. Zair)',
  'Stredoafrická republika',
  'Kongo',
  'Pobrežie Slonoviny',
  'Cookove ostrovy',
  'Čile',
  'Kamerun',
  'Čína',
  'Kolumbia',
  'Kostarika',
  'Kuba',
  'Kapverdy',
  'Curaçao',
  'Vianočný ostrov',
  'Cyprus',
  'Česko',
  'Nemecko',
  'Džibutsko',
  'Dánsko',
  'Dominika',
  'Dominikánska republika',
  'Alžírsko',
  'Ekvádor',
  'Estónsko',
  'Egypt',
  'Západná Sahara',
  'Eritrea',
  'Španielsko',
  'Etiópia',
  'Fínsko',
  'Fidži',
  'Falklandy',
  'Mikronézia',
  'Faerské ostrovy',
  'Francúzsko',
  'Gabon',
  'Spojené kráľovstvo',
  'Grenada',
  'Gruzínsko',
  'Francúzska Guyana',
  'Guernsey',
  'Ghana',
  'Gibraltár',
  'Grónsko',
  'Gambia',
  'Guinea',
  'Guadeloupe',
  'Rovníková Guinea',
  'Grécko',
  'Južná Georgia a Južné Sandwichove ostrovy',
  'Guatemala',
  'Guam',
  'Guinea-Bissau',
  'Guyana',
  'Hongkong',
  'Heardov ostrov a Macdonaldove ostrovy',
  'Honduras',
  'Chorvátsko',
  'Haiti',
  'Maďarsko',
  'Švajčiarsko',
  'Indonézia',
  'Írsko',
  'Izrael',
  'Man',
  'India',
  'Britské indickooceánske územie',
  'Irak',
  'Irán',
  'Island',
  'Taliansko',
  'Jersey',
  'Jamajka',
  'Jordánsko',
  'Japonsko',
  'Keňa',
  'Kirgizsko',
  'Kambodža',
  'Kiribati',
  'Komory',
  'Svätý Krištof a Nevis',
  'Kórejská ľudovodemokratická republika',
  'Kórejská republika',
  'Kuvajt',
  'Kajmanie ostrovy',
  'Kazachstan',
  'Laos',
  'Libanon',
  'Svätá Lucia',
  'Lichtenštajnsko',
  'Srí Lanka',
  'Libéria',
  'Lesotho',
  'Litva',
  'Luxembursko',
  'Lotyšsko',
  'Líbya',
  'Maroko',
  'Monako',
  'Moldavsko',
  'Čierna Hora',
  'Svätý Martin (francúzska časť)',
  'Madagaskar',
  'Marshallove ostrovy',
  'Macedónsko',
  'Mali',
  'Mjanmarsko',
  'Mongolsko',
  'Macao',
  'Severné Mariány',
  'Martinik',
  'Mauritánia',
  'Montserrat',
  'Malta',
  'Maurícius',
  'Maldivy',
  'Malawi',
  'Mexiko',
  'Malajzia',
  'Mozambik',
  'Namíbia',
  'Nová Kaledónia',
  'Niger',
  'Norfolk',
  'Nigéria',
  'Nikaragua',
  'Holandsko',
  'Nórsko',
  'Nepál',
  'Nauru',
  'Niue',
  'Nový Zéland',
  'Omán',
  'Panama',
  'Peru',
  'Francúzska Polynézia',
  'Papua-Nová Guinea',
  'Filipíny',
  'Pakistan',
  'Poľsko',
  'Saint Pierre a Miquelon',
  'Pitcairnove ostrovy',
  'Portoriko',
  'Palestína',
  'Portugalsko',
  'Palau',
  'Paraguaj',
  'Katar',
  'Réunion',
  'Rumunsko',
  'Srbsko',
  'Rusko',
  'Rwanda',
  'Saudská Arábia',
  'Šalamúnove ostrovy',
  'Seychely',
  'Sudán',
  'Švédsko',
  'Singapur',
  'Svätá Helena, Ascension',
  'Slovinsko',
  'Svalbard a Jan Mayen',
  'Sierra Leone',
  'San Maríno',
  'Senegal',
  'Somálsko',
  'Surinam',
  'Južný Sudán',
  'Svätý Tomáš a Princov ostrov',
  'Salvádor',
  'Svätý Martin (holandská časť)',
  'Sýria',
  'Svazijsko',
  'Turks a Caicos',
  'Čad',
  'Francúzske južné územia',
  'Togo',
  'Thajsko',
  'Tadžikistan',
  'Tokelau',
  'Východný Timor',
  'Turkménsko',
  'Tunisko',
  'Tonga',
  'Turecko',
  'Trinidad a Tobago',
  'Tuvalu',
  'Taiwan',
  'Tanzánia',
  'Ukrajina',
  'Uganda',
  'Menšie odľahlé ostrovy USA',
  'Spojené štáty, USA',
  'Uruguaj',
  'Uzbekistan',
  'Vatikán',
  'Svätý Vincent a Grenadíny',
  'Venezuela',
  'Britské Panenské ostrovy',
  'Americké Panenské ostrovy',
  'Vietnam',
  'Vanuatu',
  'Wallis a Futuna',
  'Samoa',
  'Jemen',
  'Mayotte',
  'Južná Afrika',
  'Zambia',
  'Zimbabwe',
]
