import { E2eTestUserInput } from '../../src/types/E2eTestUserInput'
import { generateRodneCislo } from '../utils/generateRodneCislo'

export const bugReport13Input: E2eTestUserInput = {
  prijem_zo_zivnosti: true,
  t1r10_prijmy: '75532.62',
  priloha3_r11_socialne: '21904.46',
  priloha3_r13_zdravotne: '29457.72',
  zaplatenePreddavky: '71417.47',
  employed: false,
  hasChildren: 'yes',
  children: [
    {
      id: 0,
      priezviskoMeno: 'Fake Child 0',
      rodneCislo: generateRodneCislo({
        turnsAge: 17,
        turnsAgeInMonth: 2,
        gender: 'MALE',
      }).pure,
      wholeYear: false,
      monthFrom: '1',
      monthTo: '3',
    },
    {
      id: 1,
      priezviskoMeno: 'Fake Child 1',
      rodneCislo: generateRodneCislo({
        turnsAge: 7,
        turnsAgeInMonth: 8,
        gender: 'FEMALE',
      }).pure,
      wholeYear: true,
      monthFrom: '0',
      monthTo: '11',
    },
    {
      id: 2,
      priezviskoMeno: 'Fake Child 2',
      rodneCislo: generateRodneCislo({
        turnsAge: 9,
        turnsAgeInMonth: 1,
        gender: 'MALE',
      }).pure,
      wholeYear: true,
      monthFrom: '4',
      monthTo: '1',
    },
    {
      id: 3,
      priezviskoMeno: 'Fake Child 3',
      rodneCislo: generateRodneCislo({
        turnsAge: 8,
        turnsAgeInMonth: 8,
        gender: 'FEMALE',
      }).pure,
      wholeYear: true,
      monthFrom: '0',
      monthTo: '11',
    },
    {
      id: 4,
      priezviskoMeno: 'Fake Child 4',
      rodneCislo: generateRodneCislo({
        turnsAge: 16,
        turnsAgeInMonth: 3,
        gender: 'FEMALE',
      }).pure,
      wholeYear: true,
      monthFrom: '0',
      monthTo: '6',
    },
  ],
  r005_meno: 'Fake',
  r004_priezvisko: 'Name',
  r001_dic: '233123123',
  r003_nace: '62010 - Počítačové programovanie',
  r007_ulica: 'Mierova',
  r008_cislo: '4',
  r009_psc: '82105',
  r010_obec: 'Bratislava 3',
  r011_stat: 'Slovensko',
  datum: '22.02.2020',
  r031_priezvisko_a_meno: 'Partner Fake',
  r031_rodne_cislo: '9609226286',
  r032_partner_pocet_mesiacov: '6',
  r032_partner_vlastne_prijmy: '4453.82',
  r032_uplatnujem_na_partnera: true,
  partner_spolocna_domacnost: true,
  partner_podmienky: {
    1: ['on'],
  },
  platil_prispevky_na_dochodok: true,
  zaplatene_prispevky_na_dochodok: '15.30',
}
