import { E2eTestUserInput } from '../../src/types/E2eTestUserInput'

export const bugReport5Input: E2eTestUserInput = {
  "t1r10_prijmy": "50805.79",
  "priloha3_r11_socialne": "4910.66",
  "priloha3_r13_zdravotne": "1914.22",
  "zaplatenePreddavky": "0",
  "r031_priezvisko_a_meno": "anon",
  "r031_rodne_cislo": "anon",
  "r032_uplatnujem_na_partnera": false,
  "partner_step": 0,
  "partner_podmienky": {},
  "r032_partner_vlastne_prijmy": "",
  "r032_partner_pocet_mesiacov": "",
  "r001_dic": "anon",
  "r003_nace": "anon",
  "meno_priezvisko": "anon",
  "r005_meno": "anon",
  "r004_priezvisko": "anon",
  "r006_titul": "",
  "r007_ulica": "anon",
  "r008_cislo": "anon",
  "r009_psc": "anon",
  "r010_obec": "anon",
  "r011_stat": "anon",
  "employed": true,
  "uhrnPrijmovOdVsetkychZamestnavatelov": "235",
  "uhrnPovinnehoPoistnehoNaSocialnePoistenie": "22.09",
  "uhrnPovinnehoPoistnehoNaZdravotnePoistenie": "9.40",
  "udajeODanovomBonuseNaDieta": "0",
  "uhrnPreddavkovNaDan": "38.67",
  "hasChildren": false,
  "children": [
    {
      "id": 0,
      "priezviskoMeno": "anon",
      "rodneCislo": "anon",
      "wholeYear": false,
      "monthFrom": "0",
      "monthTo": "11"
    }
  ],
  "prijmyPredJul22": null,
  "zaciatokPrijmovDen": null,
  "zaciatokPrijmovMesiac": null,
  "zaciatokPrijmovRok": "2022",
  "platil_prispevky_na_dochodok": true,
  "zaplatene_prispevky_na_dochodok": "180",
  "r037_pocetMesiacov": "",
  "r037_zaplatene_uroky": "",
  "expectNgoDonationPage": true,
  "XIIoddiel_uplatnujem2percenta": true,
  "splnam3per": false,
  "r142_ico": "53335082",
  "r142_obchMeno": "\"Znepokojené matky\"",
  "XIIoddiel_suhlasZaslUdaje": true,
  "iban": "anon",
  "datum": "",
  "r034a": "null.null.2022",
  "r006_titul_za": ""
}