import { E2eTestUserInput } from '../../src/types/E2eTestUserInput'
import { generateRodneCislo } from '../utils/generateRodneCislo'

export const bugReport15Input: E2eTestUserInput = {
  prijem_zo_zivnosti: true,
  t1r10_prijmy: '38621.12',
  priloha3_r11_socialne: '1544.84',
  priloha3_r13_zdravotne: '6951.80',
  zaplatenePreddavky: '6128.50',
  employed: false,
  hasChildren: 'yes',
  children: [
    {
      id: 0,
      priezviskoMeno: 'Fake Child 0',
      rodneCislo: generateRodneCislo({
        turnsAge: 16,
        turnsAgeInMonth: 10,
        gender: 'FEMALE',
      }).pure,
      wholeYear: true,
    },
    {
      id: 1,
      priezviskoMeno: 'Fake Child 1',
      rodneCislo: generateRodneCislo({
        turnsAge: 16,
        turnsAgeInMonth: 4,
        gender: 'MALE',
      }).pure,
      wholeYear: false,
      m01: false,
      m02: false,
      m03: false,
      m04: false,
      m05: false,
      m06: false,
      m07: false,
      m08: false,
      m09: true,
      m10: true,
      m11: false,
      m12: false,
    },
    {
      id: 2,
      priezviskoMeno: 'Fake Child 2',
      rodneCislo: generateRodneCislo({
        turnsAge: 16,
        turnsAgeInMonth: 4,
        gender: 'MALE',
      }).pure,
      wholeYear: true,
    },
    {
      id: 3,
      priezviskoMeno: 'Fake Child 3',
      rodneCislo: generateRodneCislo({
        turnsAge: 3,
        turnsAgeInMonth: 7,
        gender: 'FEMALE',
      }).pure,
      wholeYear: true,
    },
    {
      id: 4,
      priezviskoMeno: 'Fake Child 4',
      rodneCislo: generateRodneCislo({
        turnsAge: 15,
        turnsAgeInMonth: 8,
        gender: 'MALE',
      }).pure,
      wholeYear: false,
      m01: false,
      m02: false,
      m03: true,
      m04: true,
      m05: true,
      m06: true,
      m07: true,
      m08: false,
      m09: false,
      m10: false,
      m11: false,
      m12: false,
    },
    {
      id: 5,
      priezviskoMeno: 'Fake Child 5',
      rodneCislo: generateRodneCislo({
        turnsAge: 10,
        turnsAgeInMonth: 8,
        gender: 'MALE',
      }).pure,
      wholeYear: false,
      m01: false,
      m02: false,
      m03: false,
      m04: false,
      m05: false,
      m06: true,
      m07: true,
      m08: true,
      m09: false,
      m10: false,
      m11: false,
      m12: false,
    },
  ],
  r005_meno: 'Fake',
  r004_priezvisko: 'Name',
  r001_dic: '233123123',
  r003_nace: '62010 - Počítačové programovanie',
  r007_ulica: 'Mierova',
  r008_cislo: '4',
  r009_psc: '82105',
  r010_obec: 'Bratislava 3',
  r011_stat: 'Slovensko',
  datum: '22.02.2020',
  rent: true,
  vyskaPrijmovZPrenajmu: '8111.00',
  vydavkyZPrenajmu: '3320.64',
  prenajomPrijemZPrilezitostnejCinnosti: false,
  vyskaOslobodenia: '500',
  r035_uplatnuje_uroky: true,
  uroky_zmluva_rok_uzatvorenia: '2021',
  uroky_zmluva_mesiac_uzatvorenia: '2',
  uroky_zmluva_den_uzatvorenia: '1',
  uroky_zaciatok_urocenia_den: '21',
  uroky_zaciatok_urocenia_mesiac: '8',
  uroky_zaciatok_urocenia_rok: '2021',
  uroky_dalsi_dlznik: true,
  uroky_pocet_dlznikov: '2',
  r035_zaplatene_uroky: '1965.27',
  uroky_dalsi_uver_uplatnuje: false,
  uroky_splnam_vek_kriteria: true,
  uroky_splnam_prijem: true,
  platil_prispevky_na_dochodok: true,
  zaplatene_prispevky_na_dochodok: '2.26',
}
