name: Quality Assurance

on:
  schedule:
    - cron: '0 6 * * *'  # This cron expression runs the workflow every day at 6:00
  pull_request:
    branches: [ master ]
env:
  CURRENT_FORM_VERSION: "DPFOBv24"

jobs:
  download:
    name: Download and Process Form
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download config file
        run: wget https://edane.financnasprava.sk/java/prod/eform/config.xml -O config.xml

      - name: Filter only for Danove Priznanie Files
        run: |
          grep -i "DPFO" config.xml | grep "ElektronickyFormular" > dp.out
          cat dp.out
          ZIP_URL=$(grep -i $CURRENT_FORM_VERSION dp.out | sed -n 's/.*Url="\([^"]*\)".*/\1/p')
          echo $ZIP_URL
          wget $ZIP_URL -O form.zip

      - name: Generate MD5 Hash
        id: generate-hash
        run: |
          HASH=$(md5sum form.zip | cut -d ' ' -f 1)
          echo "hash=$HASH" >> $GITHUB_ENV

      - name: Check if branch exists for current hash
        id: check-branch
        run: |
          git fetch --all
          if git ls-remote --exit-code --heads origin update-form-${{ env.hash }}; then
            echo "branch_exists=true" >> $GITHUB_ENV
          else
            echo "branch_exists=false" >> $GITHUB_ENV
          fi

      - name: Unzip form files
        if: env.branch_exists == 'false'
        run: |
          unzip form.zip -d ./
          rm form.zip
          rm -rf ./public/form
          mkdir ./public/form
          mv ./form.* ./public/form
          FORM_FOLDER=$(find ./public/form -maxdepth 1 -type d ! -path ./public/form | head -n 1 | sed 's|./||')
          mv $FORM_FOLDER/* ./public/form
          rm -rf $FORM_FOLDER
          ls -ls ./public/form

      - name: Create new branch and commit changes
        if: env.branch_exists == 'false'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-form-${{ env.hash }}
          git add ./public/form.zip.md5 ./public/form
          git commit -m "Update form files"
          git push origin HEAD

      - name: Create Pull Request
        if: env.branch_exists == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Update form files',
              head: `update-form-${{ env.hash }}`,
              base: 'master',
              body: 'This PR updates the form files to the latest version.'
            });
            console.log(`Pull Request created at ${pullRequest.html_url}`);
